In [36]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2023-06-09 13:52:46--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.1’

input.txt.1         100%[===================>]   1.06M  3.04MB/s    in 0.3s    

2023-06-09 13:52:47 (3.04 MB/s) - ‘input.txt.1’ saved [1115394/1115394]



In [37]:
with open('input.txt', 'r' , encoding='utf-8') as f:
    text = f.read()

In [38]:
print('lenght: ', len(text))

lenght:  1115394


In [39]:
#first 100 chars
print (text[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [40]:
#Searching for all the unique characters that occur in the whole dataset
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [41]:
#Figuring out a tokenizer, chars --> to numbers using a Look out table 
stoi = {ch:i for i,ch in enumerate(chars) } #char to integer
itos = {i:ch for i,ch in enumerate(chars) } #integer to char (to make words back) ((dictionaries))
encode = lambda s: [stoi[c] for c in s] #encoder: take a string ouput a list of integer, this is a LIST (mutable)
decode = lambda l: ''.join([itos[i] for i in l]) #decoder, takes a list, uses itos to get a list of chars

print(encode('Whats up my brodolierens'))
print(decode(encode('Whats up my brodolierens')))

#okay that seems reasonable but what's lambda
#lambda is a way of not using def for code golfing reasons, fuck that. 

def enconde(s):
    return [stoi[c] for c in s]

def decode(l):
    return ''.join([itos[i] for i in l]) 

[35, 46, 39, 58, 57, 1, 59, 54, 1, 51, 63, 1, 40, 56, 53, 42, 53, 50, 47, 43, 56, 43, 52, 57]
Whats up my brodolierens


In [42]:
import torch #This is a tragedy
data = torch.tensor(encode(text) ,dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])
#Can I count the tensors that repeat? 

# frequency = {}
# for tensors in data:
#     if data in frequency:
#         frequency[data] =+1
#     else:
#         frequency[data] = 1

# print('This is the frequency', frequency)



torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [43]:
#split datalieren
n = int(0.9*len(data))
train_data = data[:n]
test_data = data[n:]

In [44]:
#data loader at last
block_size = 8
train_data[:block_size+1] #en un bloque de 9 hay 8 ejemplos. Porque el primero no cuenta. 

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [45]:
x = train_data[:block_size] #datafeed
y = train_data[1:block_size+1] #label, objetivo
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f'when input is {context} the target: {target}')

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [54]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
    #generate a small batch of data of input x and target y
    data = train_data if split == 'train' else test_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size]for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print ('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('-----------')

for b in range(batch_size): #batch dimension
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f'when input is {context.tolist()} the target: {target}')


inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
-----------
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is 